"""
Blackout Oracle - Alert Database Model.

SQLAlchemy model representing alerts generated by the Blackout Oracle
system.

Alerts may be generated from:

- Risk assessments
- Telemetry anomalies
- Weather threats
- Grid incidents
- Simulation results
- AI recommendations
- System health conditions

IMPORTANT
---------

An alert is an informational/notification record.

Creating an alert does NOT directly control any electrical-grid equipment.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


# ============================================================
# ENUMS
# ============================================================


class AlertSeverity(str, Enum):
    """
    Severity level of an alert.
    """

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """
    Current lifecycle state of an alert.
    """

    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class AlertType(str, Enum):
    """
    Category of alert generated by Blackout Oracle.
    """

    BLACKOUT_RISK = "blackout_risk"
    CASCADE_RISK = "cascade_risk"
    OVERLOAD = "overload"
    VOLTAGE_ANOMALY = "voltage_anomaly"
    FREQUENCY_ANOMALY = "frequency_anomaly"
    TELEMETRY_ANOMALY = "telemetry_anomaly"
    WEATHER = "weather"
    FLOOD = "flood"
    ASSET_FAILURE = "asset_failure"
    GENERATION_SHORTAGE = "generation_shortage"
    DEMAND_SURGE = "demand_surge"
    SYSTEM = "system"


# ============================================================
# ALERT MODEL
# ============================================================


class Alert(Base):
    """
    Database model for Blackout Oracle alerts.
    """

    __tablename__ = "alerts"

    # ========================================================
    # PRIMARY KEY
    # ========================================================

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
        default=lambda: (
            f"ALT-{uuid4().hex[:12].upper()}"
        ),
    )

    # ========================================================
    # ALERT CLASSIFICATION
    # ========================================================

    alert_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        index=True,
    )

    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=AlertStatus.ACTIVE.value,
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(300),
        nullable=False,
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # ========================================================
    # LOCATION
    # ========================================================

    region_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    region_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
    )

    latitude: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    longitude: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # GRID ASSET
    # ========================================================

    asset_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        ForeignKey(
            "assets.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    # ========================================================
    # RISK INFORMATION
    # ========================================================

    risk_score: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    blackout_probability: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    cascade_probability: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    warning_horizon_minutes: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # SOURCE INFORMATION
    # ========================================================

    source: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    source_id: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    model_name: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
    )

    model_version: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    # ========================================================
    # NOTIFICATION STATE
    # ========================================================

    notification_sent: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    notification_attempts: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    # ========================================================
    # ACKNOWLEDGEMENT
    # ========================================================

    acknowledged_by: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )

    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ========================================================
    # TIMESTAMPS
    # ========================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        onupdate=lambda: datetime.now(
            timezone.utc
        ),
    )

    # ========================================================
    # INDEXES
    # ========================================================

    __table_args__ = (
        Index(
            "ix_alerts_region_created",
            "region_id",
            "created_at",
        ),
        Index(
            "ix_alerts_asset_created",
            "asset_id",
            "created_at",
        ),
        Index(
            "ix_alerts_status_severity",
            "status",
            "severity",
        ),
    )

    # ========================================================
    # REPRESENTATION
    # ========================================================

    def __repr__(self) -> str:
        return (
            "<Alert("
            f"id='{self.id}', "
            f"type='{self.alert_type}', "
            f"severity='{self.severity}', "
            f"status='{self.status}'"
            ")>"
        )


# ============================================================
# PUBLIC EXPORTS
# ============================================================

__all__ = [
    "Alert",
    "AlertSeverity",
    "AlertStatus",
    "AlertType",
]