"""
Blackout Oracle - Recommendation Database Model.

Stores mitigation and response recommendations generated by the
Blackout Oracle risk engine, simulation engine, and AI agent.

Recommendations may include:

- Increasing generation reserve
- Redispatch recommendations
- Load-transfer recommendations
- Feeder reconfiguration recommendations
- Maintenance recommendations
- Inspection recommendations
- Emergency-response recommendations
- Weather-preparation recommendations
- Evacuation / public-safety recommendations
- Monitoring escalation
- Additional telemetry collection
- Other grid-risk mitigation strategies

A recommendation represents an ANALYTICAL PROPOSAL.

It does not represent an executed physical-grid action.

IMPORTANT
---------

Blackout Oracle must not autonomously control real electrical-grid
equipment. Recommendations should be reviewed and executed through
authorized operational procedures and systems.
"""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


# ============================================================
# ENUMS
# ============================================================


class RecommendationType:
    """
    Category of recommended action.
    """

    MONITORING = "monitoring"
    INSPECTION = "inspection"
    MAINTENANCE = "maintenance"

    GENERATION = "generation"
    RESERVE_CAPACITY = "reserve_capacity"
    REDISPATCH = "redispatch"

    LOAD_TRANSFER = "load_transfer"
    LOAD_MANAGEMENT = "load_management"

    FEEDER_RECONFIGURATION = "feeder_reconfiguration"
    NETWORK_RECONFIGURATION = "network_reconfiguration"

    EQUIPMENT_ISOLATION = "equipment_isolation"

    WEATHER_PREPARATION = "weather_preparation"
    FLOOD_RESPONSE = "flood_response"
    STORM_RESPONSE = "storm_response"

    EMERGENCY_RESPONSE = "emergency_response"
    PUBLIC_SAFETY = "public_safety"

    TELEMETRY_ESCALATION = "telemetry_escalation"

    OTHER = "other"


class RecommendationPriority:
    """
    Priority of the recommendation.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RecommendationStatus:
    """
    Lifecycle state of a recommendation.
    """

    GENERATED = "generated"
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEFERRED = "deferred"
    SIMULATING = "simulating"
    VERIFIED = "verified"
    EXECUTED = "executed"
    PARTIALLY_EXECUTED = "partially_executed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


class RecommendationSource:
    """
    Component that generated the recommendation.
    """

    RULE_ENGINE = "rule_engine"
    RISK_ENGINE = "risk_engine"
    AI_AGENT = "ai_agent"
    SIMULATION_ENGINE = "simulation_engine"
    OPERATOR = "operator"
    HYBRID = "hybrid"
    OTHER = "other"


class RecommendationApproval:
    """
    Approval state of a recommendation.
    """

    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


# ============================================================
# RECOMMENDATION MODEL
# ============================================================


class Recommendation(Base):
    """
    SQLAlchemy model representing a Blackout Oracle recommendation.
    """

    __tablename__ = "recommendations"

    # ========================================================
    # PRIMARY KEY
    # ========================================================

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
        default=lambda: (
            f"REC-{uuid4().hex[:12].upper()}"
        ),
    )

    # ========================================================
    # CLASSIFICATION
    # ========================================================

    recommendation_type: Mapped[str] = mapped_column(
        String(60),
        nullable=False,
        index=True,
    )

    priority: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=RecommendationPriority.MEDIUM,
        index=True,
    )

    status: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        default=RecommendationStatus.GENERATED,
        index=True,
    )

    source: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=RecommendationSource.OTHER,
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(300),
        nullable=False,
    )

    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    rationale: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # LOCATION
    # ========================================================

    region_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    region_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    latitude: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    longitude: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # RELATED GRID INFRASTRUCTURE
    # ========================================================

    asset_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    substation_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    feeder_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    bus_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    generator_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    # ========================================================
    # RELATED ANALYSIS
    # ========================================================

    prediction_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    incident_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    outage_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    alert_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    # ========================================================
    # RISK INFORMATION
    # ========================================================

    risk_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    blackout_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    cascade_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # PROPOSED ACTION
    # ========================================================

    action_summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    action_details: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    expected_benefit: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    expected_risk_reduction: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    estimated_load_change_mw: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    estimated_generation_change_mw: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    estimated_reserve_change_mw: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # SIMULATION
    # ========================================================

    simulation_required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    simulation_completed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    simulation_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    simulation_passed: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
    )

    simulation_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    simulation_result: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # VERIFICATION
    # ========================================================

    verification_required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    verification_completed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    verification_status: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
    )

    verification_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # HUMAN REVIEW
    # ========================================================

    human_review_required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
    )

    approval_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=RecommendationApproval.PENDING,
        index=True,
    )

    reviewed_by: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
    )

    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    rejection_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # EXECUTION INFORMATION
    # ========================================================

    execution_reference: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    execution_notes: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    executed_by: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
    )

    executed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    # ========================================================
    # AI INFORMATION
    # ========================================================

    ai_generated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        index=True,
    )

    ai_agent_name: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
    )

    ai_model_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    ai_model_version: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    ai_reasoning_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # TIME INFORMATION
    # ========================================================

    recommended_execution_time: Mapped[
        datetime | None
    ] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    # ========================================================
    # EXTERNAL INFORMATION
    # ========================================================

    external_reference: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    # ========================================================
    # CORRELATION
    # ========================================================

    request_id: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
        index=True,
    )

    correlation_id: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
        index=True,
    )

    # ========================================================
    # ADDITIONAL DATA
    # ========================================================

    metadata_json: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # TIMESTAMPS
    # ========================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        onupdate=lambda: datetime.now(
            timezone.utc
        ),
    )

    # ========================================================
    # DATABASE INDEXES
    # ========================================================

    __table_args__ = (
        Index(
            "ix_recommendations_region_type",
            "region_id",
            "recommendation_type",
        ),
        Index(
            "ix_recommendations_region_created",
            "region_id",
            "created_at",
        ),
        Index(
            "ix_recommendations_status_priority",
            "status",
            "priority",
        ),
        Index(
            "ix_recommendations_approval",
            "approval_status",
            "human_review_required",
        ),
        Index(
            "ix_recommendations_simulation",
            "simulation_required",
            "simulation_completed",
        ),
        Index(
            "ix_recommendations_asset",
            "asset_id",
        ),
        Index(
            "ix_recommendations_prediction",
            "prediction_id",
        ),
        Index(
            "ix_recommendations_incident",
            "incident_id",
        ),
    )

    # ========================================================
    # REPRESENTATION
    # ========================================================

    def __repr__(self) -> str:
        return (
            "<Recommendation("
            f"id='{self.id}', "
            f"type='{self.recommendation_type}', "
            f"priority='{self.priority}', "
            f"status='{self.status}', "
            f"approval='{self.approval_status}'"
            ")>"
        )


# ============================================================
# PUBLIC EXPORTS
# ============================================================

__all__ = [
    "Recommendation",
    "RecommendationType",
    "RecommendationPriority",
    "RecommendationStatus",
    "RecommendationSource",
    "RecommendationApproval",
]