"""
Blackout Oracle - Risk Score Database Model.

Stores quantified electrical-grid risk assessments generated by the
Blackout Oracle risk engine.

Risk scores may be calculated for:

- Regions
- Substations
- Feeders
- Buses
- Generators
- Other monitored grid assets

The risk engine can combine:

- Real-time telemetry
- Historical grid behavior
- Load and generation balance
- Voltage conditions
- Frequency conditions
- Equipment health
- Weather
- Flood risk
- Storm risk
- Temperature
- Recent incidents
- Active outages
- Network topology
- Prediction results

The resulting scores can be consumed by:

- The prediction engine
- The AI investigation agent
- The simulation engine
- Alert generation
- Recommendation generation
- Monitoring dashboards

IMPORTANT
---------

Risk scores are analytical outputs.

They do NOT directly control electrical-grid equipment.
"""


from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


# ============================================================
# ENUMS
# ============================================================


class RiskLevel:
    """
    Human-readable risk classification.
    """

    VERY_LOW = "very_low"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"
    CRITICAL = "critical"


class RiskType:
    """
    Type of risk assessment.
    """

    OVERALL = "overall"
    BLACKOUT = "blackout"
    CASCADE = "cascade"
    ASSET_FAILURE = "asset_failure"
    OVERLOAD = "overload"
    VOLTAGE = "voltage"
    FREQUENCY = "frequency"
    DEMAND = "demand"
    GENERATION = "generation"
    TRANSMISSION = "transmission"
    DISTRIBUTION = "distribution"
    WEATHER = "weather"
    FLOOD = "flood"
    STORM = "storm"
    TEMPERATURE = "temperature"


class RiskEntityType:
    """
    Type of grid entity for which the risk was calculated.
    """

    REGION = "region"
    ASSET = "asset"
    SUBSTATION = "substation"
    FEEDER = "feeder"
    BUS = "bus"
    GENERATOR = "generator"
    LOAD = "load"
    GRID = "grid"


class RiskSource:
    """
    Component that generated the risk score.
    """

    RULE_ENGINE = "rule_engine"
    ML_MODEL = "ml_model"
    STATISTICAL_MODEL = "statistical_model"
    HYBRID_MODEL = "hybrid_model"
    AI_AGENT = "ai_agent"
    SIMULATION = "simulation"
    MANUAL = "manual"
    OTHER = "other"


# ============================================================
# RISK SCORE MODEL
# ============================================================


class RiskScore(Base):
    """
    SQLAlchemy model representing a calculated grid-risk score.
    """

    __tablename__ = "risk_scores"

    # ========================================================
    # PRIMARY KEY
    # ========================================================

    id: Mapped[str] = mapped_column(
        String(50),
        primary_key=True,
        default=lambda: (
            f"RSK-{uuid4().hex[:12].upper()}"
        ),
    )

    # ========================================================
    # RISK CLASSIFICATION
    # ========================================================

    risk_type: Mapped[str] = mapped_column(
        String(60),
        nullable=False,
        index=True,
    )

    risk_level: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default=RiskLevel.LOW,
        index=True,
    )

    entity_type: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        index=True,
    )

    # ========================================================
    # TARGET ENTITY
    # ========================================================

    entity_id: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
        index=True,
    )

    entity_name: Mapped[str | None] = mapped_column(
        String(250),
        nullable=True,
    )

    region_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    region_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    asset_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    substation_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    feeder_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    bus_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    generator_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    load_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    # ========================================================
    # RISK SCORES
    # ========================================================

    score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
        index=True,
    )

    blackout_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        index=True,
    )

    cascade_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    failure_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    overload_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    voltage_instability_probability: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    frequency_instability_probability: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # RISK COMPONENTS
    # ========================================================

    telemetry_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    demand_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    generation_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    network_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    equipment_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    weather_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    flood_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    storm_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    temperature_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    historical_risk: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # GRID CONDITIONS
    # ========================================================

    current_demand_mw: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    current_generation_mw: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    available_generation_mw: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    reserve_capacity_mw: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    demand_generation_margin_mw: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # ELECTRICAL CONDITIONS
    # ========================================================

    voltage_kv: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    voltage_deviation_percent: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    frequency_hz: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    frequency_deviation_hz: Mapped[
        float | None
    ] = mapped_column(
        Float,
        nullable=True,
    )

    loading_percent: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # WEATHER CONDITIONS
    # ========================================================

    temperature_c: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    rainfall_mm: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    wind_speed_kmh: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    flood_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    storm_probability: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # ACTIVE GRID IMPACT
    # ========================================================

    active_outage_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    active_incident_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    affected_customers: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    lost_load_mw: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )

    # ========================================================
    # TIME HORIZON
    # ========================================================

    horizon_minutes: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )

    valid_from: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
    )

    valid_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    # ========================================================
    # MODEL INFORMATION
    # ========================================================

    source: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=RiskSource.OTHER,
        index=True,
    )

    model_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    model_version: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # ========================================================
    # CONFIDENCE / QUALITY
    # ========================================================

    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    data_quality_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    telemetry_completeness: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # EXPLANATION
    # ========================================================

    top_factors_json: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    explanation: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    reasoning_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # AI ANALYSIS
    # ========================================================

    ai_reviewed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        index=True,
    )

    ai_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    ai_model_name: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
    )

    ai_model_version: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    # ========================================================
    # SIMULATION
    # ========================================================

    simulation_required: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    simulation_completed: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
    )

    simulation_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    simulation_risk_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )

    # ========================================================
    # CORRELATION
    # ========================================================

    prediction_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    incident_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    outage_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    alert_id: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
    )

    correlation_id: Mapped[str | None] = mapped_column(
        String(150),
        nullable=True,
        index=True,
    )

    # ========================================================
    # ADDITIONAL DATA
    # ========================================================

    metadata_json: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # ========================================================
    # TIMESTAMPS
    # ========================================================

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        index=True,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(
            timezone.utc
        ),
        onupdate=lambda: datetime.now(
            timezone.utc
        ),
    )

    # ========================================================
    # DATABASE INDEXES
    # ========================================================

    __table_args__ = (
        Index(
            "ix_risk_scores_region_type",
            "region_id",
            "risk_type",
        ),
        Index(
            "ix_risk_scores_entity",
            "entity_type",
            "entity_id",
        ),
        Index(
            "ix_risk_scores_region_created",
            "region_id",
            "created_at",
        ),
        Index(
            "ix_risk_scores_level_score",
            "risk_level",
            "score",
        ),
        Index(
            "ix_risk_scores_blackout_cascade",
            "blackout_probability",
            "cascade_probability",
        ),
        Index(
            "ix_risk_scores_validity",
            "valid_from",
            "valid_until",
        ),
        Index(
            "ix_risk_scores_incident",
            "incident_id",
        ),
        Index(
            "ix_risk_scores_prediction",
            "prediction_id",
        ),
    )

    # ========================================================
    # REPRESENTATION
    # ========================================================

    def __repr__(self) -> str:
        return (
            "<RiskScore("
            f"id='{self.id}', "
            f"type='{self.risk_type}', "
            f"entity='{self.entity_type}', "
            f"score={self.score}, "
            f"level='{self.risk_level}'"
            ")>"
        )


# ============================================================
# PUBLIC EXPORTS
# ============================================================

__all__ = [
    "RiskScore",
    "RiskLevel",
    "RiskType",
    "RiskEntityType",
    "RiskSource",
]