"""
Blackout Oracle - Core AI Agent.

This module contains the main BlackoutOracleAgent responsible for coordinating
the investigation of potential grid incidents.

The agent is an orchestration layer. It does not perform electrical
calculations itself and does not directly control any real infrastructure.

High-level workflow:

    OBSERVE
        ↓
    DETECT
        ↓
    INVESTIGATE
        ↓
    GENERATE SCENARIOS
        ↓
    SIMULATE
        ↓
    VERIFY
        ↓
    RANK
        ↓
    REPORT
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Protocol


class AgentTool(Protocol):
    """Interface that agent tools must implement."""

    @property
    def name(self) -> str:
        """Return the tool's unique name."""
        ...

    async def execute(self, **kwargs: Any) -> Any:
        """Execute the tool with the supplied arguments."""
        ...


@dataclass
class AgentResult:
    """
    Structured result returned by the Blackout Oracle agent.

    Attributes:
        status: Final status of the investigation.
        incident_id: Identifier of the investigated incident.
        summary: Human-readable summary.
        findings: Evidence and findings collected during investigation.
        scenarios: Candidate scenarios generated by the agent.
        recommendation: Best verified recommendation, if available.
        confidence: Confidence in the overall investigation.
        timestamp: Time at which the result was generated.
    """

    status: str
    incident_id: str | None = None
    summary: str = ""
    findings: list[dict[str, Any]] = field(default_factory=list)
    scenarios: list[dict[str, Any]] = field(default_factory=list)
    recommendation: dict[str, Any] | None = None
    confidence: float = 0.0
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class BlackoutOracleAgent:
    """
    Main AI orchestration agent for Blackout Oracle.

    The agent coordinates analytical tools such as:

    - Grid-state inspection
    - Weather analysis
    - Load forecasting
    - Anomaly detection
    - Asset-failure estimation
    - Blackout-risk estimation
    - Power-system simulation
    - Scenario verification
    - Scenario ranking

    The agent itself must not perform power-system calculations or directly
    control electrical infrastructure.
    """

    def __init__(
        self,
        tools: list[AgentTool] | None = None,
        model: Any | None = None,
        max_scenarios: int = 10,
    ) -> None:
        """
        Initialize the Blackout Oracle agent.

        Args:
            tools: Analytical tools available to the agent.
            model: Optional LLM client/model. Gemini integration will be
                connected here later.
            max_scenarios: Maximum number of candidate scenarios allowed
                during an investigation.
        """
        self.model = model
        self.max_scenarios = max(1, max_scenarios)

        self._tools: dict[str, AgentTool] = {}

        for tool in tools or []:
            self.register_tool(tool)

    # ------------------------------------------------------------------
    # Tool Management
    # ------------------------------------------------------------------

    def register_tool(self, tool: AgentTool) -> None:
        """
        Register an analytical tool with the agent.

        Args:
            tool: Tool implementing the AgentTool protocol.
        """
        if not tool.name:
            raise ValueError("Agent tool must have a non-empty name.")

        self._tools[tool.name] = tool

    def get_tool(self, name: str) -> AgentTool:
        """
        Retrieve a registered tool by name.

        Args:
            name: Registered tool name.

        Returns:
            The requested tool.

        Raises:
            KeyError: If the tool is not registered.
        """
        try:
            return self._tools[name]
        except KeyError as exc:
            raise KeyError(f"Agent tool '{name}' is not registered.") from exc

    def list_tools(self) -> list[str]:
        """Return the names of all registered tools."""
        return sorted(self._tools.keys())

    # ------------------------------------------------------------------
    # Main Investigation Entry Point
    # ------------------------------------------------------------------

    async def investigate(
        self,
        incident_id: str,
        context: dict[str, Any] | None = None,
    ) -> AgentResult:
        """
        Investigate a potential grid incident.

        This is the main entry point for the agent.

        The current implementation provides the orchestration structure.
        Actual Gemini reasoning, ML models, simulation engines and data
        services will be connected as those components are implemented.

        Args:
            incident_id: Identifier of the incident.
            context: Optional initial incident context.

        Returns:
            AgentResult containing the investigation state and findings.
        """
        if not incident_id.strip():
            raise ValueError("incident_id cannot be empty.")

        context = context or {}

        findings: list[dict[str, Any]] = []
        scenarios: list[dict[str, Any]] = []

        # --------------------------------------------------------------
        # 1. OBSERVE
        # --------------------------------------------------------------

        grid_state = await self._call_tool_if_available(
            "get_grid_state",
            incident_id=incident_id,
        )

        if grid_state is not None:
            findings.append(
                {
                    "type": "grid_state",
                    "source": "get_grid_state",
                    "data": grid_state,
                }
            )

        # --------------------------------------------------------------
        # 2. WEATHER
        # --------------------------------------------------------------

        weather = await self._call_tool_if_available(
            "get_weather",
            incident_id=incident_id,
        )

        if weather is not None:
            findings.append(
                {
                    "type": "weather",
                    "source": "get_weather",
                    "data": weather,
                }
            )

        # --------------------------------------------------------------
        # 3. FORECAST
        # --------------------------------------------------------------

        forecast = await self._call_tool_if_available(
            "run_load_forecast",
            incident_id=incident_id,
        )

        if forecast is not None:
            findings.append(
                {
                    "type": "load_forecast",
                    "source": "run_load_forecast",
                    "data": forecast,
                }
            )

        # --------------------------------------------------------------
        # 4. ANOMALY DETECTION
        # --------------------------------------------------------------

        anomalies = await self._call_tool_if_available(
            "detect_anomalies",
            incident_id=incident_id,
        )

        if anomalies is not None:
            findings.append(
                {
                    "type": "anomalies",
                    "source": "detect_anomalies",
                    "data": anomalies,
                }
            )

        # --------------------------------------------------------------
        # 5. BLACKOUT RISK
        # --------------------------------------------------------------

        risk = await self._call_tool_if_available(
            "calculate_blackout_risk",
            incident_id=incident_id,
        )

        if risk is not None:
            findings.append(
                {
                    "type": "risk",
                    "source": "calculate_blackout_risk",
                    "data": risk,
                }
            )

        # --------------------------------------------------------------
        # 6. SCENARIO GENERATION
        # --------------------------------------------------------------

        generated_scenarios = await self._generate_scenarios(
            incident_id=incident_id,
            context={
                **context,
                "findings": findings,
            },
        )

        scenarios.extend(generated_scenarios[: self.max_scenarios])

        # --------------------------------------------------------------
        # 7. SIMULATE + VERIFY
        # --------------------------------------------------------------

        verified_scenarios: list[dict[str, Any]] = []

        for scenario in scenarios:
            simulation = await self._call_tool_if_available(
                "run_scenario",
                incident_id=incident_id,
                scenario=scenario,
            )

            if simulation is None:
                continue

            verification = await self._call_tool_if_available(
                "verify_scenario",
                incident_id=incident_id,
                scenario=scenario,
                simulation=simulation,
            )

            verified_scenarios.append(
                {
                    "scenario": scenario,
                    "simulation": simulation,
                    "verification": verification,
                }
            )

        # --------------------------------------------------------------
        # 8. RANK VERIFIED SCENARIOS
        # --------------------------------------------------------------

        recommendation = await self._rank_scenarios(
            incident_id=incident_id,
            scenarios=verified_scenarios,
        )

        # --------------------------------------------------------------
        # 9. RESULT
        # --------------------------------------------------------------

        confidence = self._extract_confidence(risk)

        return AgentResult(
            status="investigation_complete",
            incident_id=incident_id,
            summary=self._build_summary(
                risk=risk,
                recommendation=recommendation,
            ),
            findings=findings,
            scenarios=verified_scenarios,
            recommendation=recommendation,
            confidence=confidence,
        )

    # ------------------------------------------------------------------
    # Scenario Generation
    # ------------------------------------------------------------------

    async def _generate_scenarios(
        self,
        incident_id: str,
        context: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """
        Generate candidate mitigation scenarios.

        Gemini will eventually be used here to reason about the incident and
        propose candidate scenarios. The scenarios must subsequently be
        evaluated by the power-system simulation and verification layers.

        The LLM is not allowed to declare a scenario electrically safe.
        That decision belongs to the verification engine.
        """

        tool_result = await self._call_tool_if_available(
            "generate_scenarios",
            incident_id=incident_id,
            context=context,
        )

        if isinstance(tool_result, list):
            return tool_result

        # Safe fallback for the initial development stage.
        return [
            {
                "scenario_id": "baseline",
                "name": "Current trajectory",
                "description": "Evaluate the current grid state without intervention.",
                "changes": [],
            }
        ]

    # ------------------------------------------------------------------
    # Scenario Ranking
    # ------------------------------------------------------------------

    async def _rank_scenarios(
        self,
        incident_id: str,
        scenarios: list[dict[str, Any]],
    ) -> dict[str, Any] | None:
        """
        Rank scenarios using the dedicated ranking engine.

        The LLM must not independently decide that a scenario is optimal.
        Ranking should use verified simulation results and explicit criteria.
        """

        if not scenarios:
            return None

        result = await self._call_tool_if_available(
            "rank_scenarios",
            incident_id=incident_id,
            scenarios=scenarios,
        )

        if isinstance(result, dict):
            return result

        # Fallback: select the first verified scenario.
        for item in scenarios:
            verification = item.get("verification")

            if self._is_verified(verification):
                return {
                    "scenario_id": item.get("scenario", {}).get("scenario_id"),
                    "status": "verified",
                    "source": "fallback",
                }

        return None

    # ------------------------------------------------------------------
    # Tool Execution
    # ------------------------------------------------------------------

    async def _call_tool_if_available(
        self,
        tool_name: str,
        **kwargs: Any,
    ) -> Any | None:
        """
        Execute a registered tool if it exists.

        Missing tools do not crash the investigation during early
        development. They simply produce no result.
        """
        tool = self._tools.get(tool_name)

        if tool is None:
            return None

        return await tool.execute(**kwargs)

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_confidence(risk: Any) -> float:
        """Extract and clamp confidence from a risk result."""
        if not isinstance(risk, dict):
            return 0.0

        confidence = risk.get("confidence", 0.0)

        try:
            confidence = float(confidence)
        except (TypeError, ValueError):
            return 0.0

        return max(0.0, min(100.0, confidence))

    @staticmethod
    def _is_verified(verification: Any) -> bool:
        """Determine whether a scenario passed verification."""
        if not isinstance(verification, dict):
            return False

        status = str(verification.get("status", "")).upper()

        return status in {"VERIFIED", "PASSED", "SAFE"}

    @staticmethod
    def _build_summary(
        risk: Any,
        recommendation: dict[str, Any] | None,
    ) -> str:
        """Build a concise investigation summary."""
        if not isinstance(risk, dict):
            return "Investigation completed. Risk information is unavailable."

        risk_score = risk.get("risk_score")

        if risk_score is None:
            return "Investigation completed."

        if recommendation:
            scenario_id = recommendation.get("scenario_id", "unknown")
            return (
                f"Current estimated grid risk is {risk_score}%. "
                f"Verified scenario '{scenario_id}' is the current recommendation."
            )

        return f"Current estimated grid risk is {risk_score}%."